apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  - port: 22
    name: ssh
  selector:
    app: nginx
  type: LoadBalancer
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx
  spec:
    selector:
      matchLabels:
        app: nginx
    replicas: 1
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Never
          ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 22